#pragma once

#define BBKEY_HOMEPOS TEXT("HomePos")
#define BBKEY_PATROLPOS TEXT("PatrolPos")
#define BBKEY_TARGET TEXT("Target")
#define BBKEY_RANDOM TEXT("Random")
#define BBKEY_RUSHPOS TEXT("RushPos")
#define BBKEY_INATTACKRANGE TEXT("InAttackRange")
#define BBKEY_INALERTRANGE TEXT("InAlertRange")
#define BBKEY_ALERTDIRECT TEXT("AlertDirect")
#define BBKEY_ISREMEMBER TEXT("IsRemember")
#define BBKEY_ISRESETHOME TEXT("IsResetHome")
#define BBKEY_ISALERT TEXT("IsAlert")
#define BBKEY_NOTARGETENUM TEXT("NoTargetEnum")
#define BBKEY_STIMULUSPOS TEXT("StimulusPos")
#define BBKEY_GOHOME TEXT("GoHome")
#define BBKEY_REMEMBERTARGET TEXT("RememberTarget")